services:
  - type: web
    name: dino-server
    env: docker
    repo: https://github.com/FreSauce/dino-jobs-react.git
    rootDir: server
    numInstances: 3
    envVars:
      - key: REDIS_URL
        fromDatabase:
          type: redis
          name: dino-jobs
          property: connectionString
      - key: NODE_ENV
        value: production

  - type: web
    env: static
    name: dino-app
    repo: https://github.com/FreSauce/dino-jobs-react.git
    buildFilter:
      paths:
        - app/**
    buildCommand: yarn && yarn build --filter-frontend
    staticPublishPath: ./app/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: dino-server
          type: web
          property: hostport
